export const STORE_CATEGORY = {
	SUSHI: '스시·해산물',
	UNAGI: '장어',
	TEMPURA: '덴푸라',
	TONKATSU: '돈카츠·쿠시카츠',
	YAKITORI: '야키토리·꼬치',
	SUKIYAKI: '스키야키·샤브샤브',
	SOBA: '소바·우동',
	RAMEN: '라멘·츠케멘',
	YAKISOBA: '야키소바',
	OKONOMIYAKI: '오코노미야키·타코야키',
	DONBURI: '덮밥',
	ODEN: '오뎅',
	KAISEKI: '가이세키·일식',
	HAMBAGU: '함바그·오므라이스',
	TEPPANYAKI: '스테이크·철판요리',
	CURRY: '카레',
	YAKINIKU: '야키니쿠·호르몬',
	NABE: '나베',
	CAFE: '카페·디저트',
	IZAKAYA: '이자카야·바',
	OTHER: '기타 일본 음식',
};
